Add lie algebra adjoint operators
decargroup/pymlg pull request #14
Opened 2023-10-24 15:42 UTC by JohnKJung

2023-10-27 20:27 UTC, CharlesCossette requested changes
It would be awesome if you added a single test in the `standard_tests.py` file that makes sure these new functions work correctly. If you do that, it will be applied to ALL the groups in ALL the implementations. If I recall correctly, theres a general identity that the little adjoint should satisfy. This is the perfect thing to test for. 

https://github.com/decargroup/pymlg/blob/main/tests/standard_tests.py#L142

2023-10-27 20:27 UTC, CharlesCossette commented on pymlg/jax/se23.py
> +        A[0:3, 0:3] = Xi[0:3, 0:3]
unfortunately jax arrays dont allow this kind of indexing, you have to do something more similar to the above

2023-10-31 20:41 UTC, CharlesCossette approved these changes
awesome!

2023-10-31 20:49 UTC, CharlesCossette commented
Strange that some `SL3` tests are suddenly failure now. it looks completely unrelated to your change.

2023-10-31 21:08 UTC, JohnKJung commented
That is strange...

2023-11-01 02:59 UTC, merged

2023-11-01 03:24 UTC, CharlesCossette commented
Fixed it. It was an issue with using random numbers in the unit tests.